blog/urls.py
from django.urls import path
from . import views

from django.views.generic import TemplateView

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='blog_index'),
    path('/view/(?P<pk>\d+)',views.view_post, name='view_post'),
    path('/delete/(?P<pk>\d+)', views.entry_delete, name='entry_delete'),
    path('category/(?P<pk>\d]+)',views.view_category, name='view_category'),
    path('/edit/(?P<pk>\d+)', views.entry_update,name='entry_update'),
    #path('/edit/(?P<pk>\d+)', views.UpdateEntry.as_view(), name='entry_update'),
    path('search/', views.search, name='search'),
    path('add/', views.add_entry, name='add_entry'),
    path('resume/', views.display_resume, name='resume'),
    #path('add/', views.AddEntry.as_view(), name='add_entry'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    # ... the rest of your URLconf goes here ...
    path('', RedirectView.as_view(url='/blog')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    #path('order/', include('order.urls',namespace='order')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify


from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys



class Category(models.Model):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255)


    def __str__(self):
        return '%s' % self.name



def upload_image_to(instance, filename):
    import os
    from django.utils.timezone import now
    filename_base, filename_ext = os.path.splitext(filename)
    return 'images/%s%s' % (
        now().strftime("%Y%m%d%H%M%S"),
        filename_ext.lower(),
    )


class Entry(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    #slug = models.SlugField(max_length=145,unique=True)
    image = models.ImageField(null=True,blank=True,upload_to=upload_image_to)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return '%s' % self.title


    def __unicode__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('view_post', kwargs={'pk' : self.pk})

    def save(self,*args, **kwargs):
        # Opening the uploaded image
        if self.image:


            im = Image.open(self.image)

            output = BytesIO()

            # Resize/modify the image
            im = im.resize((750, 300),Image.NEAREST)

            # after modifications, save it to the output
            im.save(output, format='JPEG', quality=40)
            output.seek(0)

        # change the imagefield value to be the newley modifed image value
            self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)

        super(Entry, self).save(*args, **kwargs)
    # def _get_unique_slug(self):
    #
    #     #slug = slugify(self.title)
    #     unique_slug = self
    #     if Entry.objects.filter(slug=unique_slug).exists():
    #         #raise ValueError('Entry with this title already exists')
    #         print("Slug Exists")
    #         slug = unique_slug
    #     else:
    #         slug = slugify(self.title)
    #
    #     #while Entry.objects.filter(slug=unique_slug).exists():
    #     #    unique_slug = '{}-{}'.format(slug, num)
    #     #    num += 1
    #     return slug

    # def save(self, *args, **kwargs):
    #     print("This is the models idea of what the slug is: ",self)
    #     if not self.slug:
    #         self.slug = self._get_unique_slug()
    #
    #     super().save()

blog/forms.py
from .models import Entry,Category

from django import forms

class EntryModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control','placeholder' : 'Enter your text here'}))
    #slug = forms.CharField(required=False,widget=forms.TextInput(attrs={'class' : 'form-control','placeholder' : 'Slug is autogenerated if left blank'}))
    #slug = forms.CharField(required=True)

    #category = forms.CharField(initial='Blog')
    class Meta:
        model = Entry


        fields = ['title','body','image','category','created_by']

blog/views.py
from django.shortcuts import render
from django.shortcuts import render,render_to_response, get_object_or_404,redirect
from django.http import HttpResponse
# Create your views here.
# import pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Entry,Category

from django.contrib.auth.decorators import login_required

from django.forms import ModelForm
from django.views.generic.edit import UpdateView,CreateView

def index(request):
    posts = Entry.objects.all().order_by('created').reverse()
    paginator = Paginator(posts, 4)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    categories = Category.objects.all();



    return render(request, 'index.html', {'posts': posts,'categories': categories})

def view_post(request, pk):
    post = get_object_or_404(Entry, pk=pk)
    categories = Category.objects.all()

    return render(request, 'view_post.html', {'post': post,'categories' : categories})


def view_category(request, pk):
    category = get_object_or_404(Category, pk=pk)

    posts =  Entry.objects.filter(category=category)

    paginator = Paginator(posts, 4)

    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    categories = Category.objects.all()

    return render(request, 'index.html', {'posts': posts, 'categories': categories})





def search(request):
    import bleach
    search_string = bleach.clean(request.POST.get('searchString'))

    objects = Entry.objects.all()

    from model_search import model_search
    posts = model_search(search_string, objects, ['title','body'])
    categories = Category.objects.all();
    return render(request,'index.html',{'posts' : posts ,'categories' : categories})



## Form views

# myblog/views.py
from .forms import EntryModelForm
from django.urls import reverse_lazy

    # id = models.AutoField(primary_key=True)
    # title = models.CharField(max_length=255)
    # body = models.TextField()
    # slug = models.SlugField()
    # image = models.ImageField(null=True,blank=True,upload_to='static/images/')
    # category = models.ForeignKey(Category,on_delete=models.CASCADE)
    # created = models.DateTimeField(auto_now_add=True)
    # created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    # objects = SearchManager(['title','body'])


class AddEntry(CreateView):
    model = Entry
    fields = ['title','body','image','category','created_by']
    success_url = '/blog'
    template_name = 'create_blog.html'

class UpdateEntry(UpdateView):
    model = Entry
    fields = ['title', 'body', 'image', 'category', 'created_by']
    success_url = 'blog_index'
    template_name = 'create_blog.html'


@login_required
def add_entry(request):
    if request.method == 'GET':
        user = request.user
        form = EntryModelForm({'user' : user})
    else:
        # A POST request: Handle Form Upload
        # Bind data from request.POST into a PostForm
        form = EntryModelForm(request.POST)
        # If data is valid, proceeds to create a new post and redirect the user
        if form.is_valid():

            title = form.cleaned_data['title']
            body = form.cleaned_data['body']
            image =  request.FILES['image']  #form.cleaned_data['image']
            category = form.cleaned_data['category']
            #slug = form.cleaned_data['slug']
            #created = form.cleaned_data['created']
            created_by = form.cleaned_data['created_by']
            print("Value of image is: ",image)
            post = Entry.objects.create(title=title,body=body,image=image,category=category,created_by=created_by)
            #return HttpResponseRedirect(reverse(', kwargs={'post_id': post.id}))
            return redirect('/blog')

    categories = Category.objects.all()
    return render(request, 'create_blog.html', {
        'form': form,'categories' : categories
    })

#

@login_required
def entry_delete(request, pk, template_name='entry_confirm_delete.html'):
    entry = get_object_or_404(Entry, pk=pk)
    if request.method=='POST':
        entry.delete()
        return redirect('blog:blog_index')
    return render(request, template_name, {'entry':entry})



@login_required
def entry_update(request, pk, template_name='create_blog.html'):
    #entry = get_object_or_404(Entry, pk=pk)
    entry = Entry.objects.get(id=pk)
    if pk:

        entry.id = pk
        entry.title = request.POST.get('title')
        entry.body = request.POST.get('body')
        entry.category = request.POST.get('category')
        entry.save()

        return redirect('/blog')

    else:
        form = EntryModelForm(request.POST or None,instance=entry)

    return render(request, template_name, {'form':form})

def error_404(request):
    data = {}
    return render(request, '404.html', data)


def error_500(request):
    data = {}
    return render(request, '500.html', data)


def display_resume(request):
    return render(request,'resume.html')

blog/templates/aside.html
         {% load static %}
          <!-- Sidebar Widgets Column -->
          <div class="col-sm-4 float-right">
         <!-- Side Widget -->
            <div style="float:right;">
          <div class="card my-4">
            <h5 class="card-header">About Me</h5>
            <div class="card-body">
                 <img style='float:right; border-radius:1em;' width='100' heigh='100' src="https://s3.us-east-2.amazonaws.com/hashedvalue-assets/static/images/me.jpg">
            <p>Craig Riley <em>IT Leader. Old Unix Guy. Python Dude. Etc</em><br><br>
                This site is an experiment in Django and Heroku. If you happened to stumble upon this site and find anything here useful you are more than welcome to it.</p>

                <br>
                <a href="{% url 'blog:resume' %}">My Resume</a>

            </div>
          </div>

        </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>


            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                        {% for category in categories %}
                    <li>
                        <a href="{% url 'blog:view_category' pk=category.id  %}">{{ category }}</a>
                    </li>
                       {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>


</div>

blog/templates/base.html
{% load static %}
<html>
    <head>
        <title>{% block head_title %}HashedValue.com{% endblock %}</title>


        <!-- Include bootstrap cdn  -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static  "css/custom.css" %} ">
        <link rel='stylesheet' type='text/css' href='{% static 'css/font-awesome.css' %}' />

    </head>
    <body>

        {% include 'nav.html' %}
        {% block content %}


        {% endblock %}

    </body>
</html>

blog/templates/create_blog.html
{% extends 'base.html' %}
{% block title %}New Entry{% endblock %}

{% block content %}



<!-- /.blog-main -->


 <main role="main" class="container">
 <!-- Sidebar Widgets Column -->
     {% include 'aside.html' %}
      <div class="row">

        <div class="col-sm-12 blog-main">

           <form action="/blog/add/" enctype="multipart/form-data" method="POST">
                    {%csrf_token%}
                    {% for error in form.non_field_errors %}
                    <div class="form-group has-errors text-danger small">
                        {{error}}
                    </div>
                    {% endfor %}
                    {% for field in form %}
                    <div class="form-group has-errors text-danger small">
                        {{field.errors}}
                    </div>
                    <div class="form-group has-errors text-danger small">
                    </div>
                    <div class="form-group">
                        {{field}}
                    </div>
                    {% endfor %}
                    <button class="btn btn-primary" style="width:30%">Save</button>
            </form>

        </div><!-- /.blog-main -->


      </div><!-- /.row -->

    </main><!-- /.container -->


{% endblock %}

blog/templates/entry_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ entry }}" ?
    <input type="submit" value="Submit" />
</form>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome to my blog{% endblock %}
{% load markdownify %}
{% load humanize %}
{% block content %}
{% load static %}




<!-- Page Content -->
    <div class="container">








            {% include 'aside.html' %}

       <p>&nbsp;</p>
{% if posts %}

        {% for post in posts %}
        <!-- Blog Entries Column -->
 <div class="col-sm-8">

          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="https://s3.us-east-2.amazonaws.com/hashedvalue-assets/media/{{ post.image }}" >
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="card-text">{{ post.body  | markdownify | truncatewords:90}}</p>
              <a href="{% url 'blog:view_post' pk=post.id %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
             Posted {{ post.created | naturaltime }} by {{ post.created_by }}
            </div>

          </div>
        </div>



   {% endfor %}

    {% else %}
      <p>There are no posts.</p>
   {% endif %}

  <!-- Pagination -->

<div class="pagination">
    <span class="step-links  ">
         <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.<br>
        </span>

        {% if posts.has_previous %}
            <a class="btn btn-primary"  href="?page=1">&laquo; first</a>
            <a class="btn btn-primary" href="?page={{ contacts.previous_page_number }}">< previous</a>
        {% endif %}


        {% if posts.has_next %}
            <a class="btn btn-primary" href="?page={{ posts.next_page_number }}">next ></a>
            <a class="btn btn-primary" href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        <br>
        {% endif %}
    </span>
</div>

</diddv>









      </div>
    </div>




{% endblock %}

blog/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/blog">Hashedvalue.com</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog">Blog</a>
          </li>

          {% if  user %}
              <li class="nav-item">
                  <a class="nav-link disabled" href="/admin/logout">Logout {{ user }}</a>
              </li>
            {% else %}
              <li class="nav-item">
                  <a class="nav-link disabled" href="/admin/login">Login</a>
              </li>
          {% endif %}

        </ul>
        <form action='/blog/search/' method='POST' class="form-inline mt-2 mt-md-0">
             {% csrf_token %}
          <input name='searchString' class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

blog/templates/resume.html
{% extends 'base.html' %}

{% block content %}
<head>
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="css/styles.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <![endif]-->
    <script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>
</head>
<main class="container">
    <div class="wrapper">
        <div class="sidebar-wrapper">
            <div class="profile-container">
                <img class="profile" src="https://s3.us-east-2.amazonaws.com/hashedvalue-assets/static/images/me.jpg" width="120" height="120" alt="" />
                <h1 class="name">Craig Riley</h1>
                <h3 class="tagline">IT Leader - Technology Evangalist</h3>
            </div><!--//profile-container-->

            <div class="contact-container container-block">
                <ul class="list-unstyled contact-list">
                    <li class="email"><i class="fa fa-envelope"></i><a href="mailto: craigriley39@gmail.com">craigriley39@gmail.com</a></li>
                    <li class="linkedin"><i class="fa fa-linkedin"></i><a href="www.linkedin.com/in/craig-riley-b632134" target="_blank">Linked In</a></li>
                    <li class="github"><i class="fa fa-github"></i><a href="https://github.com/craigriley39" target="_blank">github.com/craigriley39</a></li>
                    <li class="twitter"><i class="fa fa-twitter"></i><a href="#" >@CraigRGraebel</a></li>
                </ul>
            </div><!--//contact-container-->




            <div class="interests-container container-block">
                <h2 class="container-block-title">Interests</h2>
                <ul class="list-unstyled interests-list">
                    <li>IT Security</li>
                    <li>Open Source Software</li>
                    <li>Linux & Unix</li>
                    <li>Python/Django</li>
                    <li>Technology</li>
                </ul>
            </div><!--//interests-->

        </div><!--//sidebar-wrapper-->

        <div class="main-wrapper">

            <section class="section summary-section">
                <h2 class="section-title"><i class="fa fa-user"></i>Career Profile</h2>
                <div class="summary">
                    <p>A proven leader that has developed and led highly efficient and successful technical teams.
                        Extensive experience and expertise in the development and execution of multi-tiered application and infrastructure systems that both raise efficiency and lower operational costs.
                        Excellent communication skills, work ethic and deep understanding of IT system architectures.
                        Ability to work with and lead the business through complex technical implementations with the goal of delivering robust and highly integrated solutions to the business.</p>
                </div><!--//summary-->
            </section><!--//section-->

            <section class="section experiences-section">
                <h2 class="section-title"><i class="fa fa-briefcase"></i>Experiences</h2>

                <div class="item">
                    <div class="meta">
                        <div class="upper-row">
                            <h3 class="job-title">Sr. VP of IT and Application Development</h3>
                            <div class="time">2015 - Present</div>
                        </div><!--//upper-row-->
                        <div class="company">Graebel Companies Inc, Aurora Co.</div>
                    </div><!--//meta-->
                    <div class="details">
                        <p>Describe your role here lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.</p>
                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                    </div><!--//details-->
                </div><!--//item-->

                <div class="item">
                    <div class="meta">
                        <div class="upper-row">
                            <h3 class="job-title">Sr. Director of IT</h3>
                            <div class="time">2014 - 2015</div>
                        </div><!--//upper-row-->
                        <div class="company">Graebel Companies Inc., Aurora Co</div>
                    </div><!--//meta-->
                    <div class="details">
                        <p>Describe your role here lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>

                    </div><!--//details-->
                </div><!--//item-->

                <div class="item">
                    <div class="meta">
                        <div class="upper-row">
                            <h3 class="job-title">Manager of IT Infrastructure</h3>
                            <div class="time">2012 - 2014</div>
                        </div><!--//upper-row-->
                        <div class="company">The Childrens Hospital Colorado, Aurora Co.</div>
                    </div><!--//meta-->
                    <div class="details">
                        <p>Describe your role here lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
                    </div><!--//details-->
                </div><!--//item-->

            </section><!--//section-->

            <section class="section projects-section">
                <h2 class="section-title"><i class="fa fa-archive"></i>Projects</h2>
                <div class="intro">
                    <p>You can list your side projects or open source libraries in this section. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus.</p>
                </div><!--//intro-->
                <div class="item">
                    <span class="project-title"><a href="#hook">Dynamics 365 for Operations</a></span> - <span class="project-tagline">Team effort to migrate our ERP from Oracle to Dynamics 365 in the cloud.</span>

                </div><!--//item-->
                <div class="item">
                    <span class="project-title"><a href="#" target="_blank">Migrate workloads to AWS</a></span> -
                    <span class="project-tagline">Migrate critical workloads to AWS - improving flexibilty and performance. </span>
                </div><!--//item-->
                <div class="item">
                    <span class="project-title"><a href="#" target="_blank">Network Retro-fit</a></span> - <span class="project-tagline">Lead team to completely replace a failing domestic network and phone system to a high-performing MPLS network. Upgrading 47 locations including offices in Prague, Singapore, London.</span>
                </div><!--//item-->
                <div class="item">
                    <span class="project-title"><a href="#" target="_blank">Electronic Medical Record System</a></span> - <span class="project-tagline">Storage and Unix engineer - implementing an electronic medical record system for the Children's Hospital Colorado. Wrote several supporting applications, application / print drivers and implemented core supporting infrastructure </span>
                </div><!--//item-->
                <div class="item">
                    <span class="project-title"><a href="#" data-toggle="popover" data-placement="right" data-content='hi there' target="_blank">Regional Data Center Move</a></span> - <span class="project-tagline">Lead storage team to migrate the entire Childrens Hospital data center to a new campus including cross site replication of 50 TB of critical patient data with minimal downtime and no data lose.</span>
                </div><!--//item-->
            </section><!--//section-->

            <section class="skills-section section">
                <h2 class="section-title"><i class="fa fa-rocket"></i>Skills &amp; Proficiency</h2>
                <div class="skillset">
                    <div class="item">
                        <h3 class="level-title">Leadership</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="98%">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->

                    <div class="item">
                        <h3 class="level-title">IT Security</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="90%">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->

                    <div class="item">
                        <h3 class="level-title">Python Scripting &amp; Automation - Django</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="60%">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->

                    <div class="item">
                        <h3 class="level-title">Linux &amp; Unix</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="85%">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->

                    <div class="item">
                        <h3 class="level-title">Enterprise Storage</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="75%">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->

                    <div class="item">
                        <h3 class="level-title">PHP, HTML/CSS</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="60%">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->

                </div>
            </section><!--//skills-section-->
        <div class="education-container container-block">
                        <h2 class="container-block-title">Certifications and Training</h2>
                        <div class="item">
                            <h6 class="degree">CISSP # 12345</h6>
                        </div><!--//item-->
                        <div class="item">
                            <h6 class="degree">GIAC GISP # 12345 </h6>
                        </div>

                    <div class="item">
                        <h6 class="degree">ITIL Foundations Certified</h6>
                    </div> <!--//item-->
                    </div><!--//education-container-->
        </div><!--//main-body-->
    </div>

    <footer class="footer">
        <div class="text-center">
                <small class="copyright">Copy right hashedvalue.com - 2017</small>
        </div><!--//container-->
    </footer><!--//footer-->

    <!-- Javascript -->
    <script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
    <script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- custom js -->
    <script type="text/javascript" src="https://s3.us-east-2.amazonaws.com/hashedvalue-assets/static/js/main.js"></script>
    </main>
</body>
</html>
{% endblock %}

blog/templates/view_post.html
{% extends 'base.html' %}
{% block head_title %}Viewing category {{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}
{% load markdownify %}
{% load humanize %}
{% block content %}

<main role="main" class="container">

    {% include 'aside.html' %}

    {% if post %}


             <div class="col-sm-12">


          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="https://s3.us-east-2.amazonaws.com/hashedvalue-assets/media/{{ post.image }}" width="750" height="300">
            <div class="card-body">
              <h1 class="card-title">{{ post.title }}</h1>
              <p class="card-text">{{ post.body  | markdownify  }} </p>
            </div>
            <div class="card-footer text-muted">
             Posted {{ post.created | naturaltime }} by {{ post.created_by }}
            </div>

          </div>
        </div>
        </div>
     </main>


    {% else %}
        <p>There are no posts.</p>
    {% endif %}
{% endblock %}